FROM python:3.10-slim

WORKDIR /app
COPY ../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY .. /app/omnisia_web
CMD ["streamlit", "run", "omnisia_web/frontend/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
